//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Siparis_Tarihi { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<int> Urun_FK { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> Musteri_FK { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<int> Mesai { get; set; }
        public Nullable<bool> Pazar { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
