//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok_Optimizasyonu
    {
        public int Id { get; set; }
        public int Urun_FK { get; set; }
        public Nullable<System.DateTime> Tahmin_Tarihi { get; set; }
        public Nullable<int> Onerilen_Miktar { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
