//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakim
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> Baslangic_Tarihi { get; set; }
        public Nullable<System.DateTime> Bitis_Tarihi { get; set; }
        public Nullable<int> Bakim_Suresi { get; set; }
        public string Bakim_Nedeni { get; set; }
    }
}
