//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<int> Maas { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public string Medeni_Durumu { get; set; }
        public Nullable<int> Cocuk_Sayisi { get; set; }
        public Nullable<int> Telefon_FK { get; set; }
        public Nullable<int> Gmail_FK { get; set; }
        public Nullable<int> Adres_FK { get; set; }
        public Nullable<int> Tc_FK { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Gmail Gmail { get; set; }
        public virtual Tc_Bilgileri Tc_Bilgileri { get; set; }
        public virtual Telefon Telefon { get; set; }
    }
}
