//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        public int Id { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> Urun_FK { get; set; }
        public Nullable<int> Ham_Madde_FK { get; set; }
    
        public virtual Ham_Madde Ham_Madde { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
