//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Recete = new HashSet<Recete>();
            this.Siparis = new HashSet<Siparis>();
            this.Stok_Optimizasyonu = new HashSet<Stok_Optimizasyonu>();
            this.Talep_Tahmini = new HashSet<Talep_Tahmini>();
        }
    
        public int Id { get; set; }
        public string Urun_Ad { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> Kategori_FK { get; set; }
        public Nullable<int> Birim_FK { get; set; }
        public string Tanim { get; set; }
        public string Kalite_Raporu { get; set; }
        public Nullable<int> Fabrika_Kapasitesi { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recete> Recete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stok_Optimizasyonu> Stok_Optimizasyonu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talep_Tahmini> Talep_Tahmini { get; set; }
    }
}
